### PR TITLE
Code Typo - Bitwise Operator where Comparison Operator Expected

### PR DESCRIPTION
**Pull request by lucanos**
Found a few instances of ">>" being used where "==" was expected.

### CODE REVIEW

**Comment by lucanos** [comment]
(The challenge of trying to make each submitted PR a separate fix - I'm going to end up with branches coming out of my ears...)

**Comment by sdunster** [comment]
Can you collapse the first 3 commits and force-push back onto this branch?

    git checkout HEAD~1 # go back one commit (discarding the last commit)
    git rebase -i HEAD~3 # interactively edit the last 3 commits
    ... pick the first, squash the second, third
    git checkout -b code_typo # create new branch
    git push -u origin code_typo # publish

**Comment by lucanos** [comment]
(Appreciating the education in GIT. I'll try and split this PR today.)

**Comment by sdunster** [comment]
Landed in:
- https://github.com/OSPFNeighbour/Lighthouse/commit/704c7255ce3c920d6a0ebd30e5bb3856621e996b
- https://github.com/OSPFNeighbour/Lighthouse/commit/64b0d4155a914580631ea3449ffc0afcd96931a5

**Pull request closed without merging**
