### PR TITLE
Various Changes

### PR DESCRIPTION
**Pull request by lucanos**
- Updated jQuery to v2.x (v1.x is for legacy browsers, but as Chrome is way ahead of IE, we can use it)
- Moved Global resources to the top of the manifest, so all subsequent files can use them (ie jQuery)
- Added Console call at the top of each file, allowing easier identification of files being called on each page

### CODE REVIEW

**Comment by sdunster** [comment]
Hey,
Thanks for putting this up. My code review may seem harsh considering the current state of the code, but please understand that I want to try and improve code quality and it starts here.

I've commented on some of your commits individually so take a look, amend your commits and/or comment back at me.

I'd love if you could let us know how extensively you've tested each change you make as well, so we can gauge how much effort we should put into testing your patches.

**Comment by sdunster** [comment]
One more thing.. I understand it's not always feasible but 1 PR per commit/collection of related changes would be excellent too. :)

**Comment by lucanos** [comment]
I greatly appreciate the feedback & suggestions. I will try and polish these submitted changes.

**Comment by lucanos** [comment]
It may be an idea to cancel this PR, as the master branch has moved on a fair way since I submitted it. And I can then submit more modular PRs focusing on single improvements for each.

**Pull request closed without merging**
